### PR TITLE
Migrate toolbox to mui v5

### PR DESCRIPTION
**Pull request by JGoggers**
This MR migrates the tool to mui v5. The toolbox will look a little different in terms of styling here and there. 

I tried to look through everything in both light and dark modes to make sure everything is in order. I could've missed some things. The changes also use some colours like #E0E0E0 that I couldn't pick up from the theme. It would be nice if you could find alternatives to hardcoded colours.

### CODE REVIEW

**Comment by drodil** [comment]
Looks promising, thanks for this! Can't wait to get this merged but take your time 🤗

**Comment by JGoggers** [comment]
@drodil could I have a review please :)

**Comment by drodil** [comment]
Thanks, looks good! Could you squash the commits a bit? These don't really follow conventional commit messages and there's a lot of WIP commits.

**Comment by JGoggers** [comment]
@drodil took a while but how do you feel about this?

**Comment by drodil** [comment]
Thanks a lot! I will take a closer look tomorrow 👌

**Comment by drodil** [comment]
Sorry, got carried away with life. I will check this soonish!

**Review by drodil — APPROVED** [review]
Looks good, I will check this locally as well

**Comment by drodil** [comment]
Thanks once again! If you want to contribute more, I have another plugin with issue to update MUI to v5 as well: https://github.com/drodil/backstage-plugin-qeta/issues/143

No pressure but if you want, I am up for all contributions, thanks!

**Comment by JGoggers** [comment]
Thanks for the offer! However, I can't contribute to this plugin at the moment 😄

**Pull request merged**
